# Generated by Django 4.2.7 on 2023-11-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ownwer',
            new_name='Owner',
        ),
    ]
