# Generated by Django 4.2.7 on 2023-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ownwer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_location', models.CharField(max_length=70)),
                ('owners', models.ManyToManyField(related_name='plants', to='api.owner')),
            ],
        ),
    ]
