# Generated by Django 4.2.7 on 2023-11-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_bus_address', models.CharField(max_length=5)),
                ('inverter_strings', models.IntegerField(max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalogger_serial', models.CharField(max_length=20)),
                ('buses_configured', models.JSONField()),
                ('plants', models.ManyToManyField(related_name='datalogger', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='DataBuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bus_name', models.CharField(max_length=5)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datalogger')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plant')),
            ],
        ),
    ]
