# Generated by Django 4.2.7 on 2023-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inverter_datalogger_databuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='inverter_strings',
            field=models.IntegerField(),
        ),
    ]
