# Generated by Django 5.0 on 2023-12-08 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_inverter_inverter_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inverter",
            name="inverter_strings",
        ),
    ]
