# Generated by Django 5.0 on 2023-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_inverter_inverter_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="inverter",
            name="inverter_configured",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
