# Generated by Django 5.0 on 2024-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_inverter_inverter_configured"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="company_name",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
