# Generated by Django 5.0 on 2024-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_owner_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="mobil",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="owner",
            name="phone",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
