# Generated by Django 5.0 on 2024-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_owner_mobil_owner_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="databuses",
            name="bus_last_address",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
