# Generated by Django 5.0 on 2024-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_databuses_bus_last_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="inverter",
            name="inverter_strings",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
