"""
Django settings for visudat project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG configuration
debug = os.getenv("DEBUG").lower()
if debug == "false":
    debug = False
else:
    debug = True
DEBUG = debug

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    # REST framework configurations
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        # Add other authentication classes as needed
    ],
}

ROOT_URLCONF = "visudat.urls"

TEMPLATES = [
    {
        # Template engine configurations
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "visudat.wsgi.application"

# Database configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation configurations
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization configurations
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE")
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images) configurations
STATIC_URL = os.getenv("STATIC_URL")

# Default primary key field type configuration
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS configurations
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
]

# Parse allowed origins from environment variable
allowed_origins = os.getenv("CORS_ALLOWED_ORIGINS")
if "," in allowed_origins:
    allowed_origins = allowed_origins.split(",")
else:
    allowed_origins = [allowed_origins]
CORS_ALLOWED_ORIGINS = allowed_origins

# CORS_ALLOW_CREDENTIALS configuration
CORS_ALLOW_CREDENTIALS = True

# Parse allowed hosts from environment variable
allowed_hosts = os.getenv("ALLOWED_HOSTS")
if "," in allowed_hosts:
    allowed_hosts = allowed_hosts.split(",")
else:
    allowed_hosts = [allowed_hosts]
ALLOWED_HOSTS = allowed_hosts

# CORS_ALLOW_HEADERS configuration
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "X-CSRFToken",
    "x-requested-with",
)

# UPLOAD DIRECTORY configuration
UPLOAD_DIRECTORY = os.getenv("UPLOAD_DIRECTORY")
