# Generated by Django 5.0.7 on 2024-08-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=70)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=70)),
                ('contact_full_name', models.CharField(blank=True, max_length=70)),
                ('contact_first_name', models.CharField(blank=True, max_length=70)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=70)),
                ('contact_mobil', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PvSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('system_street', models.CharField(max_length=70)),
                ('system_zip', models.IntegerField()),
                ('system_city', models.CharField(max_length=70)),
                ('contact_full_name', models.CharField(blank=True, max_length=70)),
                ('contact_first_name', models.CharField(blank=True, max_length=70)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=70)),
                ('contact_mobil', models.CharField(blank=True, max_length=70)),
                ('owners', models.ManyToManyField(related_name='plants', to='visudash.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_bus_address', models.CharField(max_length=5)),
                ('inverter_strings', models.IntegerField()),
                ('inverter_configured', models.JSONField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visudash.pvsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalogger_serial', models.CharField(max_length=20)),
                ('buses_configured', models.JSONField()),
                ('system', models.ManyToManyField(related_name='datalogger', to='visudash.pvsystem')),
            ],
        ),
        migrations.CreateModel(
            name='DataBuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bus', models.IntegerField()),
                ('bus_last_address', models.IntegerField()),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visudash.datalogger')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visudash.pvsystem')),
            ],
        ),
    ]
