# Generated by Django 5.0.7 on 2024-08-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visudash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataBuses',
            new_name='DataBus',
        ),
    ]
