# Generated by Django 5.0.7 on 2024-08-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visudash', '0003_alter_databus_options_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
